global:
  scrape_interval: 15s  # 4x pro Minute

scrape_configs:
  - job_name: 'wasseranlage'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.178.73:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
